# Implement your grammar here in the `grammar` variable.
# You may define additional functions, e.g. for generators.
# You may not import any other modules written by yourself.
# That is, your entire implementation must be in `grammar.py`
# and `fuzzer.py`.

grammar = {"<start>": ["<create_table>","<update_table>","<select>","<insert>","<alter_table>","<drop_table>","<create_index>","<drop_index>","<delete>","<create_trigger>","<drop_trigger>","<create_view>","<drop_view>","<attach_database>","<detach_database>","<analyze>","<begin_transaction>","<commit_transaction>","<rollback_transaction>","<create_virtual_table>","<pragma>","<built_in_aggregate>","<vacuum>;","<explain>","<indexed_by>","<savepoint>","<release>","<rollback>","<reindex>","<select_date_time>","<select_core_func>"],
           
          "<create_table>":["CREATE <temp_keyword> TABLE <if_not_clause> <qualified_table_name> <as_select> (<table_columns_def> <table_constraints>) <table_options>;"],
          "<update_table>":["<with_clause> UPDATE <or_action> <indexed_by> SET <update_list> <from_clause> <where_condition> <return_clause>;"],
          "<select>":["SELECT <select_list> <from_clause> <where_condition> <groupby_condition> <having_condition> <orderby_condition>"],
          "<insert>":["<with_clause> <insert_replace> INTO <qualified_table_name> <as_statement> (<column_list>) <end_statement> <return_clause>;"],
           "<alter_table>":["ALTER TABLE <qualified_table_name> <alter_list>;"],
          "<drop_table>":["DROP TABLE <if_clause> <table_name>;"],
           "<create_index>":["CREATE <unique_value> INDEX <if_not_clause> <index_name> ON <table_name> (<index_columns>) <where_condition>;"],
           "<drop_index>":["DROP INDEX <if_clause> <index_name>;"],
           "<delete>":["DELETE FROM <qualified_table_name> <where_condition> <return_clause>;"],
           "<create_trigger>":["CREATE TRIGGER <if_not_clause> <trigger_name> <trigger_time> <trigger_event> ON <table_name> <for_each_row> <when_clause> BEGIN <sql_statements> END;"],
           "<drop_trigger>":["DROP TRIGGER <if_clause> <trigger_clause>;"],
           "<create_view>":["CREATE <temp_keyword> VIEW <if_not_clause> <view_clause> <column_name_list> AS <select>;"],
           "<drop_view>":["DROP VIEW <if_clause> <view_clause>;"],
           "<attach_database>":["ATTACH <database_clause> <expression> AS <schema_name>;"],
           "<detach_database>":["DETACH <database_clause> <schema_name>;"],
           "<analyze>":["ANALYZE <analyze_schema> <index_or_table> <schema_table_name>;"],
           "<begin_transaction>":["<begin_statement>;"],
           "<commit_transaction>":["<commit_statement>;"],
           "<rollback_transaction>":["<rollback_statement>;"],
           "<create_virtual_table>":["CREATE VIRTUAL TABLE <if_not_clause> <qualified_table_name> USING <module_name> (<module_arguments>);"],
           "<pragma>":["PRAGMA <schema_pragma> <pragma_clause>;"],
           "<built_in_aggregate>":["<aggregate_fun> <filter_clause>;"],
           "<vacuum>":["VACUUM","VACUUM INTO <filename>","VACUUM <schema_name> INTO <filename>","VACUUM <schema_name>"],
           "<explain>":["<explain_statement> <query_statement> <sql_stmt>;"],
           "<indexed_by>":["<qualified_table_name> <as_statement> <indexed_stmt>;"],
           "<insert_replace>":["INSERT","REPLACE","INSERT <or_action>"],
           "<savepoint>":["SAVEPOINT <savepoint_name>;"],
           "<release>":["RELEASE <savepoint>","RELEASE <savepoint_name>;"],
           "<rollback>":["<rollback_clause> <savepoint>","ROLLBACK","<rollback_clause> <savepoint_name>;"],
           "<reindex>":["REINDEX <reindex-clause>;"],
           "<select_date_time>":["SELECT <date_time_function>;"],
           "<select_core_func>":["SELECT <core_function>;"],

           "<with_clause>":["","WITH RECURSIVE <common_table_expression>","WITH <common_table_expression>"],
           "<common_table_expression>":["<common_table_exp>","<common_table_expression>,<common_table_exp>"],
           "<common_table_exp>":["<table_name> (<column_list>) AS <not_material> (<select>)"],
           "<not_material>":["NOT MATERIALIZED","MATERIALIZED",""],
           "<table_options>":["","<table_option>","<table_options>,<table_option>"],
           "<table_option>":["WITHOUT ROWID","STRICT"],
           "<core_function>":["<simple_func> (<expression>)","<simple_func> (<expression>,<expression>)","<simple_func> ()","<simple_func>(*)"],
           "<simple_func>":["abs","changes","char","coalesce","concat","concat_ws","format","glob","likelihood", "likely","load_extension","load_extension","lower","ltrim","ltrim","max","min","nullif","octet_length","printf","quote","random","randomblob","replace","round","round","rtrim","rtrim","sign","soundex","sqlite_compileoption_get","sqlite_compileoption_used","sqlite_offset","sqlite_source_id","sqlite_version","substr","substr","substring","substring","total_changes","trim","trim","typeof","unhex","unhex","unicode","unlikely","upper","zeroblob"],
           "<date_time_function>":["<dt_function_name>(<dt_function_arguments>)"],
           "<dt_function_name>":["date","time","datetime","julianday","unixepoch","strftime","timediff"],
           "<dt_function_arguments>":["<string>","<string> <format>"],
           "<format>":["%Y-%m-%d", "%H:%M:%S", "%Y-%m-%d %H:%M:%S", "%m/%d/%Y", "%d-%m-%Y", "%Y%m%d", "%Y-%m-%d", "%J", "%W", "%S", "date('now')", "time('now')", "datetime('now')", "julianday('now')", "strftime('%Y-%m-%d %H:%M:%S', 'now')"],
           "<reindex-clause>":["","<collation_name>","<qualified_table_name>","<schema_name>.<index_name>","<index_name>"],
           "<rollback_clause>":["ROLLBACK TRANSACTION TO","ROLLBACK TO"],
           "<or_action>":["OR ABORT","OR FAIL","OR IGNORE","OR REPLACE","OR ROLLBACK",""],
           "<as_select>":["","AS <select>"],
           "<as_statement>":["","AS <alias>"],
           "<indexed_stmt>":["INDEXED BY <index_name>","NOT INDEXED"],
           "<explain_statement>":["","EXPLAIN"],
           "<query_statement>":["","QUERY PLAN"],
           "<savepoint_name>":["<string>"],
           "<alias>":["<string>"],
           "<sql_stmt>":["<create_table>","<update_table>","<select>","<insert>","<alter_table>","<drop_table>","<create_index>","<drop_index>","<delete>","<create_trigger>","<drop_trigger>","<create_view>","<drop_view>","<attach_database>","<detach_database>","<analyze>","<begin_transaction>","<create_virtual_table>","<pragma>","<vacuum>;"],
           "<filename>":["<integer>","<string>","<expression>","<symbol>"],
           "<aggregate_fun>":["avg(<aggregate_arguments>)","count(<aggregate_arguments>)","group_concat(<aggregate_arguments>)","min(<aggregate_arguments>)","sum(<aggregate_arguments>)","total(<aggregate_arguments>)","max(<aggregate_arguments>)","string_agg(<aggregate_arguments>)"],
           "<aggregate_arguments>":["*","","DISTINCT <expression> <orderby_condition>","<expression> <orderby_condition>","<expression>,<expression> <orderby_condition>"],
           "<from_clause>":["FROM <join_clause>","FROM <table_or_subquery>","FROM <table_or_subquery>,<table_or_subquery>",""],
           "<filter_clause>":["FILTER (WHERE <expression>)"],
           "<pragma_clause>":["","= <pragma_value>","(<pragma_value>)"],
           "<pragma_value>":["<name>","<signed-integer>","<number>","ON","OFF"],
           "<schema_pragma>":["<schema_name>.<pragma_name>","<pragma_name>"],
           "<pragma_name>":["analysis_limit","application_id","auto_vacuum","automatic_index","busy_timeout","cache_size","cache_spill", "cell_size_check","checkpoint_fullfsync","collation_list","compile_options", "data_version","database_list","defer_foreign_keys","encoding","foreign_key_check","foreign_key_list","foreign_keys","freelist_count","fullfsync","function_list","hard_heap_limit","ignore_check_constraints","incremental_vacuum","index_info","index_list","index_xinfo","integrity_check","journal_mode","journal_size_limit","legacy_alter_table","legacy_file_format","locking_mode","max_page_count","mmap_size","module_list","optimize","page_count","page_size","parser_trace","pragma_list","query_only","quick_check","read_uncommitted","recursive_triggers","reverse_unordered_selects","schema_version","secure_delete","shrink_memory","soft_heap_limit","stats","synchronous","table_info","table_list","table_xinfo","temp_store","threads","trusted_schema","user_version","vdbe_addoptrace","vdbe_debug","vdbe_listing","vdbe_trace","wal_autocheckpoint","wal_checkpoint","writable_schema"],
           "<name>":["<string>"],
           "<end_statement>":["VALUES (<list>)<upsert_or_not>","<select><upsert_or_not>","DEFAULT VALUES"],
           "<module_name>":["<string>"],
           "<module_arguments>":["<expression>","<module_arguments>,<expression>"],
           "<begin_statement>":["BEGIN <begin_transaction_clause> <transaction_statement>"],
           "<begin_transaction_clause>":["","DEFERRED","IMMEDIATE","EXCLUSIVE"],
           "<transaction_statement>":["TRANSACTION",""],
           "<commit_statement>":["<commit_transactions> <transaction_statement>"],
           "<commit_transactions>":["COMMIT","END"],
           "<rollback_statement>":["ROLLBACK <transaction_statement> <to_savepoint>"],
           "<to_savepoint>":["TO SAVEPOINT <save_pointname>","TO <save_pointname>",""],
           "<save_pointname>":["<string>"],
           "<analyze_schema>":["","<schema_name>"],          
           "<index_or_table>":["","<table_name>","<index_name>"],
           "<schema_table_name>":["","<schema_name>.<table_name>","<schema_name>.<index_name>"],
           "<database_clause>":["","DATABASE"],
           "<view_clause>":["<schema_name>.<view_name>","<view_name>"],
           "<trigger_clause>":["<schema_name>.<trigger_time>","<trigger_time>"],
           "<column_name_list>":["","(<column_list>)"],
           "<table_name>":["<string>"],
           "<view_name>":["<string>"],
           "<qualified_table_name>":["<table_name>","<schema_name>.<table_name>"],
           "<schema_name>":["<string>"],
           "<temp_keyword>":["TEMP","TEMPORARY",""],
           "<return_clause>":["","RETURNING <expression>","*","RETURNING <expression> <as_statement>","RETURNING <expression> <alias>"],
          "<alter_list>":["<rename_table>","<rename_column>","<add_column>","<drop_column>"],
           "<rename_table>":["RENAME TO <table_name>"],
           "<rename_column>":["RENAME COLUMN <column_name> TO <column_name>","RENAME <column_name> TO <column_name>"],
           "<add_column>":["ADD COLUMN <table_columns_def>","ADD <table_columns_def>"],
           "<drop_column>":["DROP COLUMN <column_name>","DROP <column_name>"],
           "<upsert_or_not>":["<upsert_commands>",""],
           "<upsert_commands>":["ON CONFLICT <conflict_target> DO <upsert_actions>"],
           "<upsert_actions>":["NOTHING","UPDATE SET <update_list> <where_condition>"],
           "<unique_value>":["","UNIQUE"],
           "<if_clause>":["","IF EXISTS"],
           "<if_not_clause>":["","IF NOT EXISTS"],
           "<index_name>":["<string>"],
           "<index_columns>":["<index_column>","<index_columns>,<index_column>"],
           "<index_column>":["<column_name> <collate_clause> <sort_clause>","<expression> <collate_clause> <sort_clause>"],
           "<collate_clause>":["","COLLATE <collation_name>"],
           "<collation_name>":["<string>"],
           "<sort_clause>":["ASC","DESC",""],
          "<table_columns_def>":["<table_column_def>","<table_columns_def>,<table_column_def>"],
          "<table_column_def>":["<column_name> <type_name> <column_constraints>"],
           "<update_list>":["<update_assignment>","<update_list>,<update_assignment>"],
           "<update_assignment>":["<column_name> = <expression>"],
           "<conflict_target>":["<column_name>","(<column_list>)"], 
           "<column_list>":["<column_name>","<column_list>,<column_name>"],
           "<column_name>":["<string>"],
           "<where_condition>":["","WHERE <expression>"],
           "<groupby_condition>":["","GROUP BY <list>"],
           "<having_condition>":["","HAVING <expression>"],
           "<list>":["<expression>","<list>,<expression>"],
           "<orderby_condition>":["","ORDER BY <orderby_list>"],
           "<orderby_list>":["<term>","<orderby_list>,<term>"],
           "<term>":["<expression>","<expression> ASC","<expression> DESC","<expression> NULLS FIRST","<expression> NULLS LAST","<expression> <collate_clause>"],
           "<table_constraints>":["",",<table_constraint>","CONSTRAINT <name> <table_constraint>"],
           "<table_constraint>":["PRIMARY KEY (<indexed_columns>) <conflict_clause>","UNIQUE (<indexed_column>) <conflict_clause>","FOREIGN KEY <column_list> <foreign_key_clause>","CHECK (<expression>)"],
           "<indexed_columns>":["<indexed_column>","<indexed_columns>,<indexed_column>"],
           "<indexed_column>":["<column_name>","<column_name> <collate_clause>","<column_name> <collate_clause><sort_clause>","<column_name> <sort_clause>","<expression>","<expression> <collate_clause>","<expression> <collate_clause> <sort_clause>","<expression> <sort_clause>"],
           "<foreign_key_clause>":["REFERENCES <table_name> (<column_list>) <foreign_terms> <deferrable_clause>"],
           "<foreign_terms>":["","ON <foreign_actions> <foreign_parameters>","MATCH <name>"],
           "<foreign_parameters>":["SET NULL","SET DEFAULT","CASCADE","RESTRICT","NO ACTION"],
           "<foreign_actions>":["DELETE","UPDATE"],
           "<deferrable_clause>":["","<deferrable>","<not_deferrable>"],
           "<deferrable>":["DEFERRABLE","DEFERRABLE INITIALLY DEFERRED","DEFERRABLE INITIALLY IMMEDIATE",""],
           "<not_deferrable>":["NOT DEFERRABLE","NOT DEFERRABLE INITIALLY DEFERRED","NOT DEFERRABLE INITIALLY IMMEDIATE",""],
           "<column_constraints>":["","<column_constraint>","CONSTRAINT<name> <column_constraint>"],
           "<column_constraint>":["PRIMARY KEY <conflict_clause> <increment>","UNIQUE <conflict_clause>","<foreign_key_clause>","CHECK (<expression>)","NOT NULL <conflict_clause>","DEFAULT (<expression>)","COLLATE <collation_name>","","AS (<expression>)","<generated> AS (<expression>) <store>"],
           "<store>":["","STORED","VIRTUAL"],
           "<generated>":["","GENERATED ALWAYS"],
           "<conflict_clause>":["","ON CONFLICT <conflict_action>"],
           "<conflict_action>":["ROLLBACK","ABORT","FAIL","IGNORE","REPLACE"],
           "<increment>":["","AUTOINCREMENT"],
           "<expression>":["<column_name>","<literal_value>","<function_call>","<qualified_table_name>.<column_name>","<expression><binary_operator><expression>","<unary_operator><expression>","(<expression>,<expression>)","CAST (<expression> AS <type_name>)","<expression> <collate_clause>","<expression> <null_values>","<expression> <between_values> <expression> AND <expression>","<expression> <exp_operators> <expression> <escape_clause>","<expression> <is_clause> <distinct> <expression>","<expression> <not_term> (<exp_not_term>)","<expression> <not_term> <qualified_table_name>","<not_exists_clause> (<select>)","<case> <when_clause> <else_term> END","<raise_func>"],

           "<raise_func>":["RAISE (<action>)"],
           "<action>":["IGNORE","ROLLBACK,<error_message>","ABORT,<error_message>","FAIL,<error_message>"],
           "<else_term>":["","ELSE <expression>"],
           "<error_message>":["<string>"],
           "<when_clause>":["WHEN <expression> THEN <expression>","<when_clause>,<when_clause>"],
           "<case>":["CASE","CASE <expression>"],
           "<not_exists_clause>":["","NOT EXISTS","EXISTS"],
           "<exp_not_term>":["<select>","","<expression>","<expression>,<expression>"],
           "<is_clause>":["IS","IS NOT"],
           "<not_term>":["IN","NOT IN"],
           "<distinct>":["DISTINCT FROM",""],
           "<exp_operators>":["NOT LIKE","NOT GLOB","NOT REGEXP","NOT MATCH","LIKE","GLOB","REGEXP","MATCH"],
           "<between_values>":["NOT BETWEEN","BETWEEN"],
           "<unary_operator>":["+","++","-","--","!"],
           "<escape_clause>":["","ESCAPE <expression>"],
           "<null_values>":["ISNULL","NOTNULL","NOT NULL"],
           "<type_name>":["<name>","<name><name>","(<signed-integer>)","(<signed-integer>,<signed-integer>)","INTEGER","REAL","TEXT","BLOB"],
           "<function_call>":["<function_name>(<arguments>) <filter_clause> <over_clause>"],
           "<function_name>":["<string>"],
           "<over_clause>":["OVER <window_name>","OVER ()","OVER (<base_window_name>)"],
           "<window_name>":["<string>"],
           "<base_window_name>":["<string>"],
           "<arguments>":["<expression>","<expression>,<arguments>"],
           "<select_list>":["*","<expression>"],
           "<trigger_name>":["<string>"],
           "<trigger_time>":["BEFORE","AFTER","INSTEAD OF"],
           "<trigger_event>":["DELETE","INSERT","UPDATE","UPDATE OF <column_name>"],
           "<for_each_row>":["FOR EACH ROW",""],
           "<when_clause>":["","WHEN <expression>"],
           "<sql_statements>":["<sql_statement>","<sql_statements> <sql_statement>"],
           "<sql_statement>":["<update_table>","<delete>","<insert>","<select>"],
           "<table_or_subquery>":["<table_name>","(<select>)","<table_or_subquery>, <table_or_subquery>","(<join_clause>)","<indexed_by>"],
           "<join_clause>":["<table_or_subquery>","<table_or_subquery> <join_operator> <table_or_subquery> <join_constraint>"],
           "<join_operator>":[",","<join_values> JOIN"],
           "<join_values>":["","NATURAL","CROSS","INNER","LEFT","RIGHT","FULL","LEFT OUTER","RIGHT OUTER","FULL OUTER"],
           "<join_constraint>":["ON <expression>","USING (<column_list>)",""],
           "<binary_operator>":["=","!=","<",">","<=",">=","&&","||","+","-","*","/"],
           "<literal_value>":["<integer>","<float>","<string>","NULL","TRUE","FALSE","CURRENT_TIME","CURRENT_DATE","CURRENT_TIMESTAMP"],
           "<string>":["<letter>","<letter><string>"],
           "<symbol>":["!","@","#","$","%","^","&","*","(",")","-","_","+","="],
           "<integer>":["<signed-integer>","<signed-integer><integer>"],
           "<signed-integer>":["+<digit>","-<digit>"],
           "<float>":["<integer>.<integer>"],
          "<letter>":["a","b","c","d","e","f","g","h","i","j","k","l","m","n","o","p","q","r","s","t","u","v","w","x","y","z","A","B","C","D","E","F","G","H","I","J","K","L","M","N","O","P","Q","R","S","T","U","V","W","X","Y","Z"],
        "<digit>":["<number>","<digit><number>"],
           "<number>":["0","1","2","3","4","5","6","7","8","9"],
          }